# Build stage
FROM node:18-alpine AS build
WORKDIR /app/client
COPY client/package*.json ./
RUN npm install
COPY client .
RUN npm run build

# Runtime stage with only production files
FROM node:18-alpine
WORKDIR /app/client
COPY --from=build /app/client/node_modules ./node_modules
COPY --from=build /app/client/.next ./.next
COPY --from=build /app/client/public ./public
COPY --from=build /app/client/package*.json ./
COPY --from=build /app/client/next.config.js ./
CMD ["npm", "start"]
